spring:
  application:
    name: user

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: SuperSecret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 8082

